// <auto-generated />
namespace EFCodeFirstProject.MainMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedStatustoOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedStatustoOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201706121244040_Added Status to Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
